
// --- DATA ANGGOTA (Berdasarkan Rekap Chat) ---
export const membersData = [
  { 
    id: 1, 
    name: "Taufik Rahman", 
    age: "35", 
    business: "Sewa Kipas Blower Krisbow", 
    category: "Jasa & Sewa", 
    duration: "5 Tahun", 
    location: "Menteng Raya", 
    ig: "taufik.krisbow",
    description: "Penyedia solusi pendingin udara outdoor terbaik di Medan. Menggunakan unit Krisbow original untuk menjamin kesejukan acara Anda.",
    services: ["Sewa Kipas Blower", "Pengadaan Unit Krisbow", "Maintenance Pendingin"],
    contact: "6281263608999",
    address: "Jl. Menteng Raya No. 45, Medan Denai"
  },
  { 
    id: 2, 
    name: "Renanda", 
    age: "35", 
    business: "Mateen Toys Rental & Konsultan Sosmed", 
    category: "Jasa & Sewa", 
    duration: "5 Tahun", 
    location: "Sikambing", 
    ig: "mateentoysrental",
    description: "Jasa sewa dan laundry perlengkapan bayi seperti stroller, carseat, box bayi, dan mainan anak. Juga melayani jasa Brand/Social Media Consultant.",
    services: ["Sewa Perlengkapan Bayi", "Laundry Stroller", "Social Media Consultant"],
    contact: "6281394445144",
    address: "Jl. Jawa, Sikambing, Medan"
  },
  { 
    id: 3, 
    name: "Olivia", 
    age: "29", 
    business: "Central Cookies", 
    category: "F&B", 
    duration: "3 Tahun", 
    location: "Menteng Raya", 
    ig: "centralcookies.id",
    description: "Produsen kue kering homemade premium di Medan. Menyediakan berbagai varian cookies untuk hantaran, sekolah, dan reseller.",
    services: ["Aneka Kue Kering", "Hampers Hari Raya", "Reseller Program"],
    contact: "6282258352235",
    address: "Menteng Raya, Medan Denai"
  },
  { 
    id: 4, 
    name: "Yusuf Alwi", 
    age: "27", 
    business: "ANT Printing & Jasa Outbound", 
    category: "Agensi & IT", 
    duration: "5 Tahun", 
    location: "Johor", 
    ig: "antprinting24",
    description: "Visual Design, Digital Printing, dan Marketing. Menyediakan juga jasa Outbound untuk corporate dan komunitas.",
    services: ["Digital Printing", "Visual Design", "Jasa Outbound"],
    contact: "6281262837646",
    address: "Johor, Medan"
  },
  { 
    id: 5, 
    name: "Wisyral", 
    age: "41", 
    business: "Grosir Sembako", 
    category: "Retail & Grosir", 
    duration: "Baru Merintis", 
    location: "Simpang Selayang", 
    ig: "ical.valenskie",
    description: "Pusat grosir sembako kebutuhan harian dengan harga bersaing untuk mitra toko dan rumah tangga.",
    services: ["Suplai Sembako", "Kemitraan Toko", "Retail Sembako"],
    contact: "6281260010811",
    address: "Komp. Pemda Tk.I Simp. Selayang"
  },
  { 
    id: 6, 
    name: "Robana", 
    age: "30", 
    business: "Bana Durian (Olahan Durian)", 
    category: "F&B", 
    duration: "10 Tahun", 
    location: "Delitua", 
    ig: "banadurian.id",
    description: "Pusat aneka olahan durian premium di Medan. Menyediakan durian kupas, pancake durian, dan dessert durian lainnya.",
    services: ["Durian Kupas", "Pancake Durian", "Hampers Durian"],
    contact: "62812000000",
    address: "Delitua, Medan"
  },
  { 
    id: 7, 
    name: "Daisy", 
    age: "35", 
    business: "Distributor Beras", 
    category: "Retail & Grosir", 
    duration: "3 Tahun", 
    location: "KM 12", 
    ig: "",
    description: "Distributor beras kualitas unggul. Melayani pesanan hingga 500 kg dengan layanan antar gratis di wilayah Medan.",
    services: ["Suplai Beras", "Free Ongkir Medan", "Bantuan Sosial"],
    contact: "6281374917657",
    address: "KM 12, Medan"
  },
  { 
    id: 8, 
    name: "Septani Bagariang", 
    age: "35", 
    business: "Pakaian Online & Offline", 
    category: "Retail & Grosir", 
    duration: "8 Tahun", 
    location: "Asam Kumbang", 
    ig: "septani_bagariang",
    description: "Menjual berbagai jenis pakaian fashion terbaru untuk pria dan wanita melalui platform online maupun toko fisik.",
    services: ["Pakaian Ready Stock", "Online Shop", "Grosir Hijab"],
    contact: "6282374166566",
    address: "Asam Kumbang, Medan"
  },
  { 
    id: 9, 
    name: "Mhd Ramadhan Arvin", 
    age: "23", 
    business: "Hazael Gaming (Software & Topup)", 
    category: "Agensi & IT", 
    duration: "4 Tahun", 
    location: "Medan Area", 
    ig: "hazaelgaming.store",
    description: "Jasa pembuatan website, software custom, dan pusat top-up game digital terpercaya.",
    services: ["Web Development", "Software Design", "Topup Game Digital"],
    contact: "6282367057520",
    address: "Medan Area"
  },
  { 
    id: 10, 
    name: "Sahlan Sahputra", 
    age: "37", 
    business: "Alan Mutual Property", 
    category: "Properti & Konstruksi", 
    duration: "1 Tahun", 
    location: "Pancing", 
    ig: "alan_mutualproperty",
    description: "Konsultan properti ahli untuk jual beli rumah subsidi maupun komersial. Membantu investasi properti di Medan.",
    services: ["Jual Beli Rumah", "Rumah Subsidi", "Investasi Properti"],
    contact: "62812000000",
    address: "Pancing, Medan"
  },
  { 
    id: 11, 
    name: "Firdausi Maulida Nasyaa", 
    age: "27", 
    business: "Diaz Konveksi", 
    category: "Jasa & Sewa", 
    duration: "5 Tahun", 
    location: "Tembung", 
    ig: "diazkonveksi.id",
    description: "Layanan jasa konveksi untuk seragam, kaos komunitas, dan berbagai kebutuhan tekstil lainnya dengan kualitas rapi.",
    services: ["Seragam Kantor", "Kaos Komunitas", "Produksi Tekstil"],
    contact: "6282274507682",
    address: "Tembung Ps 11, Medan"
  },
  { 
    id: 12, 
    name: "Ichsan", 
    age: "28", 
    business: "Sudut Rekaan (Desain Sosmed)", 
    category: "Agensi & IT", 
    duration: "2 Tahun", 
    location: "Johor", 
    ig: "sudut.rekaan",
    description: "Jasa desain grafis khusus untuk konten media sosial bisnis untuk meningkatkan engagement dan visual brand.",
    services: ["Social Media Design", "Branding Identity", "Content Planning"],
    contact: "62895611353518",
    address: "Medan Johor"
  },
  { 
    id: 13, 
    name: "Ridho Robbi Pasi", 
    age: "20", 
    business: "Digital Techno ID", 
    category: "Agensi & IT", 
    duration: "6 Bulan", 
    location: "Selayang", 
    ig: "digitaltechno.id",
    description: "Solusi digitalisasi UMKM dan bisnis menengah ke atas. Membantu transformasi digital menuju otomasi dan skalabilitas.",
    services: ["Digital Transformation", "App Development", "IT Consulting"],
    contact: "62812000000",
    address: "Medan Selayang"
  },
  { 
    id: 14, 
    name: "Delievia", 
    age: "25", 
    business: "Varian Brownies & Delkuki", 
    category: "F&B", 
    duration: "9 Tahun", 
    location: "Denai", 
    ig: "varianbrownies",
    description: "Spesialis Dessert & Cakes. Menyediakan brownies lumer dan cookies premium dengan resep turun temurun khas Medan.",
    services: ["Brownies Lumer", "Cookies Premium", "Dessert Box"],
    contact: "6285761933298",
    address: "Medan Denai"
  },
  { 
    id: 15, 
    name: "Nancy", 
    age: "26", 
    business: "Toko Sembako Nancy", 
    category: "Retail & Grosir", 
    duration: "2 Tahun", 
    location: "Amplas", 
    ig: "shopee:nancymnrng",
    description: "Toko sembako terpadu yang melayani penjualan offline dan online melalui marketplace untuk kemudahan akses bahan pokok.",
    services: ["Retail Sembako", "Online Marketplace", "Kebutuhan Rumah Tangga"],
    contact: "6281263608999",
    address: "Medan Amplas"
  },
  { 
    id: 16, 
    name: "Bayu / Mia", 
    age: "-", 
    business: "Rumah Protein Medan", 
    category: "F&B", 
    duration: "4 Bulan", 
    location: "Johor", 
    ig: "rumahprotein.medan",
    description: "Pusat olahan protein bergizi untuk gaya hidup sehat masyarakat Medan.",
    services: ["Olahan Daging", "Protein Supply", "Healty Food"],
    contact: "6281377079443",
    address: "Medan Johor"
  },
  { 
    id: 17, 
    name: "Tony", 
    age: "46", 
    business: "Konstruksi & Content Creator", 
    category: "Properti & Konstruksi", 
    duration: "10 Tahun", 
    location: "Kapuk Raya", 
    ig: "tony_richcreator",
    description: "Supplier genset, perakitan panel, dan tim konstruksi infrastruktur industri. Juga aktif sebagai kreator konten digital.",
    services: ["Supplier Genset", "Instalasi PLN", "Konstruksi Industri"],
    contact: "6285647502619",
    address: "Jl. Kapuk Raya 1, Medan"
  },
  { 
    id: 18, 
    name: "Jhon Vebrianto Girsang", 
    age: "26", 
    business: "Hutacode Software House", 
    category: "Agensi & IT", 
    duration: "5 Tahun", 
    location: "Kota", 
    ig: "hutacode",
    description: "Software House yang berfokus pada pengembangan aplikasi mobile, web, dan sistem informasi perusahaan.",
    services: ["Custom Software", "Mobile App Dev", "IT Support"],
    contact: "6282274040496",
    address: "Jl. SM Raja, Medan Kota"
  },
  { 
    id: 19, 
    name: "Alda", 
    age: "23", 
    business: "Moment Creates (Video Editor)", 
    category: "Agensi & IT", 
    duration: "1 Tahun", 
    location: "Medan", 
    ig: "momentcreates",
    description: "Wedding & Event Content Creator serta Video Editor profesional untuk mendokumentasikan momen berharga Anda.",
    services: ["Video Wedding", "Event Documentation", "Social Media Editing"],
    contact: "6287812272824",
    address: "Medan"
  },
  { 
    id: 20, 
    name: "Seawris Pinnan", 
    age: "47", 
    business: "TWS Certified Consultant", 
    category: "Jasa & Sewa", 
    duration: "7 Tahun", 
    location: "Katamso", 
    ig: "seawris_pinnan",
    description: "Konsultan tersertifikasi TWS untuk membantu optimalisasi sistem dan operasional bisnis Anda.",
    services: ["Business Consulting", "System Audit", "Operation Training"],
    contact: "6289664077272",
    address: "Katamso - Titi Kuning"
  },
  { 
    id: 21, 
    name: "Fauza", 
    age: "27", 
    business: "Travel & Mental Health Therapy", 
    category: "Jasa & Sewa", 
    duration: "1.5 Tahun", 
    location: "Aceh / Medan", 
    ig: "healingwanita_id",
    description: "Travel agency khusus healing dan layanan konseling kesehatan mental untuk wanita (Healing Wanita ID).",
    services: ["Travel Packages", "Mental Health Counseling", "Healing Program"],
    contact: "6282344301522",
    address: "Aceh & Medan"
  },
  { 
    id: 22, 
    name: "Hilal", 
    age: "29", 
    business: "Celup Juaro & Travel Umroh", 
    category: "F&B", 
    duration: "1 Tahun", 
    location: "Tembung", 
    ig: "celupjuaroo",
    description: "Bisnis kuliner 'Celup Juaro' dan penyedia layanan travel Umroh terpercaya di Medan.",
    services: ["Produk Kuliner", "Layanan Umroh", "Tour & Travel"],
    contact: "6282188514242",
    address: "Medan Tembung"
  },
  { 
    id: 23, 
    name: "Fajrur Alkilany", 
    age: "30", 
    business: "Alto Rent Car & Hamsa Filter Air", 
    category: "Jasa & Sewa", 
    duration: "5 Tahun", 
    location: "Marelan", 
    ig: "altorentcar.medan",
    description: "Layanan sewa mobil (Alto Rent Car) dan pemasangan filter air bersih (Hamsa Filter Air).",
    services: ["Rental Mobil", "Instalasi Filter Air", "Maintenance Air"],
    contact: "62812000000",
    address: "Marelan V Psr 2 Barat"
  },
  { 
    id: 24, 
    name: "Fendy Chandra", 
    age: "30", 
    business: "Grosir Kabel Ties", 
    category: "Retail & Grosir", 
    duration: "2 Bulan", 
    location: "Helvetia", 
    ig: "fendy_caw",
    description: "Pusat grosir kabel ties untuk kebutuhan kabeling, otomotif, dan industri di wilayah Medan.",
    services: ["Grosir Kabel Ties", "Material Handling", "Hardware Supply"],
    contact: "6285370181469",
    address: "Helvetia, Medan"
  },
  { 
    id: 25, 
    name: "Novriadi Antonius", 
    age: "31", 
    business: "Web Dev & Lyora Laundry", 
    category: "Agensi & IT", 
    duration: "7 Tahun", 
    location: "Ngumban Surbakti", 
    ig: "lyoralaundry",
    description: "Pakar IT dengan fokus Web Development dan startup top-up game. Juga mengoperasikan Lyora Laundry.",
    services: ["Web Development", "Laundry Service", "Startup Consulting"],
    contact: "6285373711010",
    address: "Jl. Ngumban Surbakti, Medan"
  },
  { 
    id: 26, 
    name: "Adel", 
    age: "23", 
    business: "Affiliatepreneur & Teri Mamamia", 
    category: "F&B", 
    duration: "6 Tahun", 
    location: "Medan Deli", 
    ig: "terimedanmamamia",
    description: "Ekspektasi tinggi pada affiliate marketing dan bisnis makanan olahan khas Medan 'Teri Medan Mamamia'.",
    services: ["Teri Medan Olahan", "Affiliate Mentoring", "Digital Marketing"],
    contact: "6281220360668",
    address: "Medan Deli"
  },
  { 
    id: 27, 
    name: "Diah Fardhani (Dini)", 
    age: "36", 
    business: "Matsuna Matcha", 
    category: "F&B", 
    duration: "Baru Merintis", 
    location: "Tuntungan", 
    ig: "matsunamatcha",
    description: "Minuman Matcha premium dengan rasa otentik Jepang untuk menemani hari-hari Anda di Medan.",
    services: ["Matcha Drink", "Powder Matcha Supply", "Event Beverage"],
    contact: "6281361619445",
    address: "Medan Tuntungan"
  },
  { 
    id: 28, 
    name: "Siska Helmy", 
    age: "47", 
    business: "Souvenir Boneka Flanel", 
    category: "Retail & Grosir", 
    duration: "Sejak 2018", 
    location: "Binjai", 
    ig: "siskahelmy",
    description: "Pengrajin kreatif boneka flanel untuk souvenir pernikahan, kado ulang tahun, dan aksesoris unik.",
    services: ["Boneka Flanel Custom", "Souvenir Pernikahan", "Handicraft Training"],
    contact: "62895333974646",
    address: "Jl. T. Imam Bonjol, Binjai"
  },
  { 
    id: 29, 
    name: "Taufiq", 
    age: "33", 
    business: "Produksi Tusuk Sate", 
    category: "Pertanian & Peternakan", 
    duration: "2 Tahun", 
    location: "Hamparan Perak", 
    ig: "-",
    description: "Produksi massal tusuk sate berkualitas dari bambu pilihan untuk kebutuhan UMKM kuliner.",
    services: ["Suplai Tusuk Sate", "Pemesanan Partai Besar", "Layanan Grosir"],
    contact: "6285218088442",
    address: "Desa Bulu Cina, Hamparan Perak"
  },
  { 
    id: 30, 
    name: "Fikri Fatah Markies", 
    age: "50", 
    business: "Fifa Architect & Interior", 
    category: "Properti & Konstruksi", 
    duration: "1.5 Tahun", 
    location: "Johor", 
    ig: "fifa_architect_medan",
    description: "Biro arsitektur profesional yang melayani jasa desain bangunan, interior, furnish, dan fabrikasi furnitur.",
    services: ["Desain Arsitektur", "Interior Design", "Fabrikasi Furniture"],
    contact: "6282161056288",
    address: "Medan Johor"
  },
  { 
    id: 31, 
    name: "Jennie", 
    age: "25", 
    business: "Handmade Crochet (Rajut)", 
    category: "Retail & Grosir", 
    duration: "1 Tahun", 
    location: "Aceh / Medan", 
    ig: "aisyav_crochet",
    description: "Produk rajutan tangan (crochet) berkualitas tinggi mulai dari amigurumi, tas, hingga aksesoris fashion.",
    services: ["Tas Rajut", "Boneka Rajut", "Custom Crochet"],
    contact: "6283831945824",
    address: "Banda Aceh"
  },
  { 
    id: 32, 
    name: "Maria", 
    age: "26", 
    business: "Florist & Hampers", 
    category: "Jasa & Sewa", 
    duration: "1 Tahun", 
    location: "Medan", 
    ig: "mareeia.flo",
    description: "Layanan penyediaan rangkaian bunga (Florist) dan paket hampers untuk berbagai acara spesial.",
    services: ["Bouquet Bunga", "Hampers Souvenir", "Dekorasi Event Mini"],
    contact: "6285333664703",
    address: "Medan"
  },
  { 
    id: 33, 
    name: "Tina Siahaan", 
    age: "30", 
    business: "Preloved Pakaian & Tas", 
    category: "Retail & Grosir", 
    duration: "4 Tahun", 
    location: "Helvetia", 
    ig: "autin_autin",
    description: "Menyediakan pakaian dan tas preloved (secondhand) bermerk dengan kondisi istimewa dan harga terjangkau.",
    services: ["Preloved Branded", "Thrifting Shop", "Resell Package"],
    contact: "6285362094180",
    address: "Pajak Helvetia, Medan"
  },
  { 
    id: 34, 
    name: "Muhammad Rizki (Dedek)", 
    age: "24", 
    business: "3 Dimensi Interior & MBS", 
    category: "Properti & Konstruksi", 
    duration: "4 Tahun", 
    location: "Helvetia", 
    ig: "3dimensiinterior",
    description: "Kontraktor & manajemen proyek interior. Serta Medan Bumbu Supply (suplai logistik bumbu resto).",
    services: ["Manajemen Proyek Interior", "Suplai Bumbu Resto", "Sayur Logistik"],
    contact: "6281273696239",
    address: "Jl. Gaperta, Medan Helvetia"
  },
  { 
    id: 35, 
    name: "Evi", 
    age: "41", 
    business: "Bengkel Mobil (27 Tahun)", 
    category: "Otomotif", 
    duration: "27 Tahun", 
    location: "Batang Hari", 
    ig: "elvie_mariatti",
    description: "Bengkel mobil berpengalaman selama puluhan tahun di Medan. Melayani servis berkala, perbaikan mesin, dan body repair.",
    services: ["Servis Mobil", "Overhaul Mesin", "Maintenance Berkala"],
    contact: "6282166218006",
    address: "Jl. Sei Batang Hari, Medan"
  },
  { 
    id: 36, 
    name: "Arie Pilliank", 
    age: "35", 
    business: "Photographer & Project", 
    category: "Jasa & Sewa", 
    duration: "4 Tahun", 
    location: "Amaliun", 
    ig: "ariepilliank",
    description: "Professional Photographer untuk wedding, pre-wedding, dan corporate project dengan sentuhan estetik.",
    services: ["Wedding Photography", "Commercial Photography", "Editing Service"],
    contact: "6285179712085",
    address: "Jl. Amaliun, Medan"
  },
  { 
    id: 37, 
    name: "Marduansyah", 
    age: "33", 
    business: "Ath Thufail Farm (Peternakan)", 
    category: "Pertanian & Peternakan", 
    duration: "6 Tahun", 
    location: "Johor", 
    ig: "aththufailfarm.id",
    description: "Peternakan kambing yang menyediakan susu kambing murni, kambing aqiqah, dan hewan kurban berkualitas.",
    services: ["Kambing Aqiqah", "Susu Kambing Murni", "Hewan Kurban"],
    contact: "6281260621367",
    address: "Medan Johor & Laut Dendang"
  },
  { 
    id: 38, 
    name: "Vendrie Yulman", 
    age: "25", 
    business: "Accel Learning & Homia.io", 
    category: "Pendidikan", 
    duration: "2 Tahun", 
    location: "Medan", 
    ig: "accel_learning_indonesia",
    description: "Kursus bahasa (HSK, IELTS, TOEFL) dan penyedia sistem kasir digital POS (Homia.io).",
    services: ["Pelatihan Bahasa", "Sistem Kasir Digital", "IT Business Solution"],
    contact: "6287777340516",
    address: "Medan"
  },
  { 
    id: 39, 
    name: "Fransisco Sihaloho", 
    age: "45", 
    business: "General Contractor & Supplier", 
    category: "Properti & Konstruksi", 
    duration: "20 Tahun", 
    location: "Selayang", 
    ig: "-",
    description: "Kontraktor umum dan supplier material konstruksi dengan pengalaman dua dekade melayani proyek di Sumatera Utara.",
    services: ["Civil Engineering", "Material Supply", "Contracting"],
    contact: "6281273102500",
    address: "Jl. Abdul Hakim No.17, Medan Selayang"
  },
  { 
    id: 40, 
    name: "Eka Suradi Jaya", 
    age: "34", 
    business: "Konstruksi & Pengelasan", 
    category: "Properti & Konstruksi", 
    duration: "6 Tahun", 
    location: "Binjai", 
    ig: "-",
    description: "Layanan teknik renovasi rumah, pengelasan, dan pengerjaan konstruksi baja berat/ringan.",
    services: ["Renovasi Rumah", "Pengelasan", "Konstruksi Baja"],
    contact: "6287823810534",
    address: "Kota Binjai"
  },
  { 
    id: 41, 
    name: "Fayzah / Fay", 
    age: "24", 
    business: "Pangsit Pedas Arreksa", 
    category: "F&B", 
    duration: "1 Tahun", 
    location: "Marelan", 
    ig: "fayyin_arreksa",
    description: "Kuliner kekinian berfokus pada varian pangsit pedas dengan resep rahasia yang menggugah selera.",
    services: ["Pangsit Goreng Pedas", "Snack Retail", "Food Delivery"],
    contact: "6281361561382",
    address: "Medan Marelan"
  },
  { 
    id: 42, 
    name: "Melwin Gunawan", 
    age: "28", 
    business: "Supplier Atap & Plafon", 
    category: "Properti & Konstruksi", 
    duration: "5 Tahun", 
    location: "Medan-Binjai", 
    ig: "mhdmelwin_",
    description: "Supplier dan aplikator spesialis peratap an dan per plafon an untuk estetika bangunan yang kokoh.",
    services: ["Instalasi Plafon PVC", "Pemasangan Atap", "Supplier Bahan Bangunan"],
    contact: "6282160622002",
    address: "Perbatasan Medan-Binjai"
  },
  { 
    id: 43, 
    name: "Calvin Kristio", 
    age: "26", 
    business: "Medan Bangunan & 3D Print", 
    category: "Properti & Konstruksi", 
    duration: "3 Tahun", 
    location: "Ringroad", 
    ig: "medanbangunan",
    description: "Toko bahan bangunan modern dan jasa desain/produksi prototipe berbasis 3D Printing.",
    services: ["Material Bangunan", "3D Printing Service", "Prototipe Produk"],
    contact: "6287855051999",
    address: "Jl. Ringroad, Simp Asoka, Medan"
  },
  { 
    id: 44, 
    name: "Dian", 
    age: "35", 
    business: "Fashion & Thrift Store", 
    category: "Retail & Grosir", 
    duration: "6 Tahun", 
    location: "Delitua", 
    ig: "-",
    description: "Menyediakan berbagai pilihan fashion modern dan koleksi thrift (bekas berkualitas) pilihan.",
    services: ["Fashion Retail", "Thrifting", "Aksesoris Fashion"],
    contact: "62882015812919",
    address: "Delitua, Medan"
  },
  { 
    id: 45, 
    name: "Henny Tobing", 
    age: "37", 
    business: "Maneo English Class", 
    category: "Pendidikan", 
    duration: "6 Bulan", 
    location: "Online", 
    ig: "maneo.englishclass",
    description: "Bimbel edukatif untuk anak-anak meliputi calistung dan penguasaan bahasa asing (Inggris, Jepang, Mandarin, Korea).",
    services: ["Kursus Calistung", "Bahasa Inggris Anak", "Kelas Privat Online"],
    contact: "628116120026",
    address: "Online & Home Service"
  },
  { 
    id: 46, 
    name: "Nisah", 
    age: "39", 
    business: "OMakeup Store (Skincare)", 
    category: "Retail & Grosir", 
    duration: "12 Tahun", 
    location: "Patumbak", 
    ig: "omakeupstore",
    description: "Pusat produk kecantikan, skincare, dan parfum original untuk memenuhi kebutuhan gaya hidup Anda.",
    services: ["Retail Skincare", "Parfum Branded", "Konsultasi Kecantikan"],
    contact: "628197265310",
    address: "Medan Patumbak"
  },
  { 
    id: 47, 
    name: "Titin", 
    age: "30", 
    business: "Tsurayya Playschool", 
    category: "Pendidikan", 
    duration: "3 Tahun", 
    location: "Johor", 
    ig: "tsurayyaps.id",
    description: "Playschool kreatif untuk anak usia dini (2-5 tahun) dengan fokus pada perkembangan minat dan bakat.",
    services: ["Daycare & Playschool", "Program Calistung", "Early Childhood Education"],
    contact: "6283198621628",
    address: "Medan Johor"
  },
  { 
    id: 48, 
    name: "James Jay", 
    age: "39", 
    business: "Gemilang Solusi Mandiri", 
    category: "Jasa & Sewa", 
    duration: "1.5 Tahun", 
    location: "Jakarta/Medan", 
    ig: "-",
    description: "Perusahaan yang berfokus pada pengadaan biomassa (cangkang sawit) untuk kebutuhan energi industri.",
    services: ["Suplai Biomassa", "Cangkang Sawit", "Energi Alternatif"],
    contact: "6287770287070",
    address: "Menara Astra, Jakarta (Asli Medan)"
  },
  { 
    id: 49, 
    name: "Kenn", 
    age: "20", 
    business: "Cafe & Home Service Carwash", 
    category: "F&B", 
    duration: "Baru Merintis", 
    location: "Nibung", 
    ig: "-",
    description: "Entrepreneur muda yang sedang mengembangkan bisnis cafe di Nibung dan layanan cuci mobil panggil.",
    services: ["Cafe Hospitality", "Service Carwash", "Layanan Panggilan"],
    contact: "628126943718",
    address: "Medan"
  },
  { 
    id: 50, 
    name: "Indah Lestari", 
    age: "30", 
    business: "Crochet & Macrame Artist", 
    category: "Retail & Grosir", 
    duration: "Sejak 2019", 
    location: "Mabar", 
    ig: "indahlestarimrg",
    description: "Kreator seni rajut (crochet) dan macrame untuk dekorasi rumah dan aksesoris yang berseni tinggi.",
    services: ["Macrame Decoration", "Rajut Fashion", "Handicraft Custom"],
    contact: "6285220266909",
    address: "Jl. KL Yos Sudarso, Mabar"
  },
  { 
    id: 51, 
    name: "Ari Tajudin", 
    age: "40", 
    business: "MC, WO/EO & Property", 
    category: "Jasa & Sewa", 
    duration: "2 Tahun", 
    location: "Sunggal", 
    ig: "ari.tajudin",
    description: "Professional Master of Ceremony (MC), Wedding Organizer, Event Organizer, dan agen properti terpercaya.",
    services: ["Professional MC", "Wedding Organizer", "Jual Beli Properti"],
    contact: "62895611060773",
    address: "Medan Sunggal"
  },
  { 
    id: 52, 
    name: "Yusrizal", 
    age: "37", 
    business: "Heytax (Tax Consultant)", 
    category: "Jasa & Sewa", 
    duration: "17 Tahun", 
    location: "Medan", 
    ig: "heytax.id",
    description: "Pakar pajak profesional dengan pengalaman puluhan tahun membantu kepatuhan pajak perusahaan dan individu.",
    services: ["Tax Planning", "Audit Pajak", "Laporan Keuangan"],
    contact: "6285297888008",
    address: "Medan"
  },
  { 
    id: 53, 
    name: "Ruth Andriani", 
    age: "38", 
    business: "Laundry & Ayam Petelur", 
    category: "Pertanian & Peternakan", 
    duration: "4 Tahun", 
    location: "Medan", 
    ig: "andrianiruth",
    description: "Mengoperasikan jasa laundry profesional dan peternakan ayam petelur skala menengah.",
    services: ["Laundry Service", "Telur Ayam Segar", "Livestock Management"],
    contact: "6281226042790",
    address: "Medan"
  },
  { 
    id: 54, 
    name: "Galih Subagus", 
    age: "37", 
    business: "Rumah Grosir Medan", 
    category: "Retail & Grosir", 
    duration: "2 Tahun", 
    location: "Platina", 
    ig: "rumahgrosirmedan",
    description: "Pusat grosir barang rumah tangga dan kebutuhan harian dengan harga distributor.",
    services: ["Grosir Household", "Distributor Barang", "Retail Toko"],
    contact: "628116120026",
    address: "Jl. Platina 4, Medan"
  },
  { 
    id: 55, 
    name: "Fani", 
    age: "27", 
    business: "Sagisun (Donat Kentang)", 
    category: "F&B", 
    duration: "Sejak 2021", 
    location: "L. Pakam", 
    ig: "sagisunfoodies_",
    description: "Produsen donat kentang lumer (frozen food) yang lezat dan praktis untuk dikonsumsi kapan saja.",
    services: ["Donat Kentang Frozen", "Snack Supplier", "Layanan Pesan Antar"],
    contact: "6282258352235",
    address: "Medan & Lubuk Pakam"
  },
  { 
    id: 56, 
    name: "Ilham Fahmi", 
    age: "31", 
    business: "Onlineshop Sepatu Bromo", 
    category: "Retail & Grosir", 
    duration: "3 Tahun", 
    location: "Bromo", 
    ig: "ilhamfahmi166",
    description: "Pusat penjualan sepatu secara online yang melayani pengiriman seluruh Indonesia dari pangkalan Bromo Medan.",
    services: ["Sepatu Fashion", "Sneakers Ready Stock", "Pengiriman Cargo"],
    contact: "6287844486095",
    address: "Jl. Bromo, Medan"
  },
  { 
    id: 57, 
    name: "Dina Maylinda", 
    age: "35", 
    business: "Ailana Kids Apparel", 
    category: "Retail & Grosir", 
    duration: "6 Tahun", 
    location: "H. Perak", 
    ig: "ailanakidsbabyshop",
    description: "Fashion khusus anak-anak dan bayi dengan bahan berkualitas dan desain yang nyaman dipakai harian.",
    services: ["Baju Anak Branded", "Pakaian Bayi", "Fashion Anak Daily"],
    contact: "6285360390396",
    address: "Medan Hamparan Perak"
  },
  { 
    id: 58, 
    name: "Sabda Arian", 
    age: "28", 
    business: "Suplai Ayam Potong", 
    category: "Pertanian & Peternakan", 
    duration: "2 Bulan", 
    location: "Marelan", 
    ig: "sabdaarianmprII",
    description: "Penyedia daging ayam potong segar untuk kebutuhan rumah tangga dan usaha kuliner di wilayah Marelan.",
    services: ["Suplai Ayam Segar", "Ayam Potong Berkualitas", "Layanan Antar"],
    contact: "6285261401542",
    address: "Marelan, Medan"
  },
  { 
    id: 59, 
    name: "Gagas Pangestu", 
    age: "28", 
    business: "Travel Umroh & Sekolah", 
    category: "Jasa & Sewa", 
    duration: "12 Tahun Edu", 
    location: "Tembung", 
    ig: "Facebook: Gagas Pangestu",
    description: "Praktisi pendidikan di sekolah dan penyedia jasa keberangkatan ibadah Umroh dengan pendampingan penuh.",
    services: ["Layanan Ibadah Umroh", "Manajemen Sekolah", "Tour Religi"],
    contact: "6282385566696",
    address: "Jl. Sederhana Psr 7, Tembung"
  },
  { 
    id: 60, 
    name: "Irwansyah (Iwansarlep)", 
    age: "53", 
    business: "Iwansarlep Event Organizer", 
    category: "Jasa & Sewa", 
    duration: "Sejak 2011", 
    location: "K. Lalang", 
    ig: "iwansarlep",
    description: "Event Organizer berpengalaman selama belasan tahun yang melayani berbagai jenis acara mulai dari formal hingga entertainment.",
    services: ["Manajemen Event", "EO Entertainment", "Talent Management"],
    contact: "6289603030444",
    address: "Jl. Kelambir Lima, K. Lalang"
  },
  { 
    id: 61, 
    name: "Faisal Bazrah Siregar", 
    age: "31", 
    business: "Agen BriliNK Fazra", 
    category: "Jasa & Sewa", 
    duration: "2 Tahun", 
    location: "R. Prapat", 
    ig: "faisalbazrahsiregar",
    description: "Layanan jasa perbankan Agen BriliNK untuk memudahkan masyarakat dalam transaksi keuangan kapan saja.",
    services: ["Transfer Antar Bank", "Pembayaran Tagihan", "Tarik Tunai"],
    contact: "6281370259091",
    address: "Rantauprapat"
  }
];

export const statsData = [
  { label: "Total Anggota", value: "Over 100", icon: "Users" },
  { label: "Sektor Bisnis", value: "15+", icon: "Briefcase" },
  { label: "Total Produk", value: "500+", icon: "ShoppingBag" }
];

export const eventsData = [
  { 
    id: 1, 
    title: "Kopdar Perdana #1: Sinergi UMKM", 
    day: "15", 
    month: "APR", 
    location: "Medan (TBA)", 
    type: "Offline Event",
    desc: "Pertemuan fisik perdana untuk merapatkan shaf bisnis dan membangun kolaborasi nyata antar anggota."
  },
  { 
    id: 2, 
    title: "Webinar: Strategi Digital Brand", 
    day: "22", 
    month: "MEI", 
    location: "Zoom Meeting", 
    type: "Online Session",
    desc: "Diskusi mendalam bersama pakar branding tentang cara meningkatkan nilai jual bisnis di era digital."
  }
];

export const opportunitiesData = [
  { 
    id: 1, 
    title: "Penawaran Lahan 2.5 Hektar", 
    desc: "Lahan strategis untuk manufaktur atau produksi skala ekspor. Hubungi Sahlan untuk detail legalitas.", 
    type: "Kolaborasi Properti", 
    postedBy: "Sahlan",
    icon: "car" 
  },
  { 
    id: 2, 
    title: "Suplai Beras Skala Besar", 
    desc: "Butuh relasi untuk suplai beras supermarket. Daisy siap mensuplai hingga 500kg free ongkir.", 
    type: "Supply Order", 
    postedBy: "Daisy",
    icon: "shopping-bag" 
  },
  { 
    id: 3, 
    title: "Tim Media Kopdar", 
    desc: "Dibutuhkan relawan tim dokumentasi (Shooting/Video) untuk acara Kopdar perdana.", 
    type: "Community Event", 
    postedBy: "Admin Firda",
    icon: "video" 
  }
];
